# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vxbS512tG3obYQUohSfka84zAhMSJOPz
"""

import streamlit as st
import pandas as pd
import pickle

# ================================
# PAGE CONFIG
# ================================
st.set_page_config(page_title="Customer Churn App", layout="centered")

# ================================
# LOAD MODEL
# ================================
model = pickle.load(open("model.pkl", "rb"))

# ================================
# TITLE
# ================================
st.title("🛍️ Customer Churn Prediction System")
st.write("Enter customer details to predict churn status")

st.divider()

# ================================
# INPUT SECTION
# ================================
st.subheader("🧾 Customer Details")

col1, col2 = st.columns(2)

with col1:
    total_orders = st.number_input("Total Orders", min_value=1, value=5, key="orders")
    total_revenue = st.number_input("Total Revenue", min_value=0.0, value=1000.0, key="revenue")

with col2:
    avg_order_value = st.number_input("Average Order Value", min_value=0.0, value=200.0, key="aov")
    lifespan_days = st.number_input("Customer Lifespan (days)", min_value=1, value=100, key="lifespan")

st.divider()

# ================================
# CREATE INPUT DATA
# ================================
input_data = pd.DataFrame([[
    total_orders,
    total_revenue,
    avg_order_value,
    lifespan_days
]], columns=[
    'total_orders',
    'total_revenue',
    'avg_order_value',
    'lifespan_days'
])

# ================================
# PREDICTION
# ================================
if st.button("🔍 Predict Customer Status"):

    prediction = model.predict(input_data)[0]

    st.subheader("📢 Prediction Result")

    if prediction == 2:
        st.error("⚠️ High Risk: Customer will CHURN")
        st.write("👉 Action: Offer discount & re-engagement campaign")

    elif prediction == 1:
        st.warning("⚡ Medium Risk: Customer is AT RISK")
        st.write("👉 Action: Send personalized recommendations")

    else:
        st.success("✅ Customer is ACTIVE")
        st.write("👉 Action: Retain with loyalty programs")

    st.divider()

    st.subheader("📊 Input Summary")
    st.dataframe(input_data)

